Repository Persistent-SS13/Persistent-Bay, pull requests merged in 2018-10, with the labels that each got.

#770 Allow long distance holocalls
  code/game/machinery/hologram.dm
  html/changelogs/rhicora-pr-770.yml
Labels: Awaiting Review

#769 Fix borgos in main
  code/game/machinery/portable_turret.dm
  html/changelogs/rhicora-pr-769.yml
Labels: Awaiting Review

#766 Finite duct tape
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/weapons/tape.dm
  code/modules/clothing/spacesuits/breaches.dm
  code/modules/projectiles/guns/magnetic/magnetic_construction.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/supermatter/supermatter.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/other.dm
  html/changelogs/PsyCommando-PR-766.yml
Labels: Approved for DEV, Feature Change

#782 Fixes not being able to pickup small animals
  code/game/objects/structures/stasis_cage.dm
Labels: Approved for DEV, Approved for MAIN, Fix

#771 Revert "Update bioprinter.dm"
  code/game/machinery/bioprinter.dm
Labels: Approved for DEV, Approved for MAIN, Fix

#773 Do not qdel cortical stacks in the Recycler
  code/game/machinery/recycler.dm
Labels: Approved for DEV, Approved for MAIN, Fix

#791 Allows mining borgs to traverse the asteroid
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Approved for DEV, Approved for MAIN, Feature Change

#780 Fixed Rotation Range (And Rotating While Incapacitated)
  code/game/machinery/pipe/construction.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
  code/modules/recycling/disposal-construction.dm
Labels: Approved for DEV, Fix

#761 Add duct tape crates
  code/datums/supplypacks/supply.dm
  html/changelogs/PsyCommando-PR-761.yml
Labels: Approved for DEV, Feature Change

#790 Properly identify borgos that don't have access
  code/game/machinery/portable_turret.dm
Labels: Awaiting Author

#803 Add bulk cable supply pack
  code/datums/supplypacks/engineering.dm
  html/changelogs/PsyCommando-PR-803.yml
Labels: Approved for DEV, Feature Change

#808 Deconstructible and buildable suit storage and cycler
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/weapons/circuitboards/machinery/suit_storage_unit.dm
  code/modules/research/designs.dm
  html/changelogs/PsyCommando-PR-808.yml
  persistentss13.dme
Labels: Approved for DEV, Feature Change, Fix

#810 Deconstructible bridge computer
  code/modules/shuttles/shuttle_console.dm
  html/changelogs/PsyCommando-PR-810.yml
Labels: Approved for DEV, Fix

#811 Fix mirrored mixer and mirrored filters disconnecting on reload
  code/modules/atmospherics/components/trinary_devices/filter.dm
  code/modules/atmospherics/components/trinary_devices/mixer.dm
Labels: Approved for DEV, Fix

#897 Gun Sprite Changes (Fixed)
  html/changelogs/TheGreatRevanchist.yml
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun.dmi
Labels: Feature Change

#906 Makes the master controller start itself.
  code/controllers/master.dm
Labels: Awaiting Review, Fix, Hotfix

#899 Sushi & Costumes
  code/datums/supplypacks/hospitality.dm
  code/datums/supplypacks/nonessent.dm
  code/game/machinery/kitchen/microwave.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/reagent_containers/food/snacks/fish.dm
  code/modules/reagents/reagent_containers/food/sushi.dm
  html/changelogs/sushicostume.yml
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/sushi.dmi
  persistentss13.dme
Labels: New Feature

#909 Som Revert
  code/__defines/atmospherics.dm
  code/__defines/math_physics.dm
  code/_helpers/global_access.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/objects/effects/chem/chempuddle.dm
  code/game/objects/effects/chem/drain.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/structures/watercloset.dm
  code/modules/ZAS/Zone.dm
  code/modules/_chemistry_update/ARO.dm
  code/modules/_chemistry_update/chempuddle.dm
  code/modules/_chemistry_update/drain.dm
  code/modules/_chemistry_update/hooks.dm
  code/modules/atmospherics/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/components/unary/outlet_injector.dm
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/xgm/gases.dm
  code/modules/xgm/xgm_gas_data.dm
  html/changelogs/ingles-pr-909.yml
  persistentss13.dme
  test/run-test.sh
Labels: Hotfix

#918 Fixes various bugs with guns
  code/game/machinery/cell_charger.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/temperature.dm
  code/modules/projectiles/guns/projectile.dm
Labels: Approved for DEV, Fix

#887 Revert "Update bioprinter.dm"
  code/game/machinery/bioprinter.dm
Labels: Approved for DEV, Fix

#814 Higher jam chance for ballistics, lower miss chance for lasers
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  html/changelogs/rhicora-pr-814.yml
Labels: Approved for DEV, Feature Change

#914 Readds hand-rolled cigarettes crafting recipe and other smoking related items
  code/datums/supplypacks/nonessent.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/materials/material_recipes.dm
  html/changelogs/ourpar-PR-914.yml
  icons/mob/mask.dmi
Labels: Approved for DEV, New Feature

#920 Changes to energy weapon charging
  code/game/machinery/recharger.dm
  code/game/objects/items/weapons/circuitboards/machinery/recharge_station.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/research/designs.dm
  html/changelogs/NataKilar-PR-920.yml
Labels: Feature Change

#921 Craftablesv1
  code/datums/supplypacks/assignments.dm
  code/game/objects/items/shooting_range.dm
  code/game/objects/items/weapons/circuitboards/machinery/recharge_station.dm
  code/game/objects/items/weapons/defib.dm
  code/game/objects/structures/target_stake.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/materials/material_recipes.dm
  code/modules/research/designs.dm
  config/example/admins.txt
  icons/mob/uniform.dmi
  icons/obj/clothing/personalized.dmi
Labels: Feature Change, New Feature

#942 Fix accessory verbs not restoring after save
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/clothing/under/accessories/ties.dm
Labels: Awaiting Review

#941 Fix microwave repairing
  code/game/machinery/kitchen/microwave.dm
Labels: Awaiting Review

#933 Gives suit cyclers core accesses (and some other fixes)
  code/game/machinery/autolathe_datums.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/assembly/proximity.dm
  html/changelogs/ourpar-PR-933.yml
Labels: Awaiting Review

#925 Add extra control to vents via air alarms
  code/game/machinery/alarm.dm
  nano/templates/air_alarm.tmpl
Labels: Awaiting Review, New Feature
