Repository Persistent-SS13/Persistent-Bay, pull requests merged in 2018-11, with the labels that each got.

#978 Sleeper now requires chemicals in order to operate.
  code/game/machinery/Sleeper.dm
Labels: Approved for DEV, Fix

#990 Add floodlights to supplyapp
  code/datums/supplypacks/engineering.dm
  code/game/machinery/floodlight.dm
  sound/machines/switch-big-power.ogg
Labels: Approved for DEV, Awaiting Travis, New Feature

#991 Adds Unathi Hissing
  code/modules/emotes/definitions/_species.dm
  code/modules/emotes/definitions/audible.dm
  sound/voice/unathihiss.ogg
Labels: Approved for DEV, Awaiting Travis, New Feature

#999 SSasteroid
  code/__defines/map.dm
  code/_helpers/global_access.dm
  code/_macros.dm
  code/controllers/aggression_controller.dm
  code/controllers/master_controller.dm
  code/controllers/subsystems/asteroid.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/mob/living/simple_animal/hostile/voxslug.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  html/changelogs/Andrew - 999.yml
  persistentss13.dme
  test/run-test.sh
Labels: Awaiting Review, Feature Change

#1004 re-adds some lost clothing
  code/modules/clothing/under/miscellaneous.dm
  html/changelogs/ourpar-PR-1004.yml
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Approved for DEV, Fix

#1009 Admin ghost can now change job assignment
  code/modules/modular_computers/file_system/programs/command/card.dm
Labels: Approved for DEV, New Feature

#994 Un-commented the commented gun code
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
Labels: Awaiting Author, Feature Change

#1023 Wall and related icon fixes
  code/game/machinery/alarm.dm
  code/game/objects/structures.dm
  code/game/turfs/simulated/wall_icon.dm
  code/modules/materials/definitions/materials_glass.dm
  code/modules/materials/definitions/materials_organic.dm
  code/modules/materials/definitions/materials_stone.dm
  icons/obj/monitors.dmi
  icons/turf/wall_masks.dmi
Labels: Approved for DEV, Awaiting Travis, Fix

#993 Fix cells and air content respawning on reload
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/atmoalter/portable_atmospherics.dm
  code/game/machinery/atmoalter/pump.dm
  code/game/machinery/atmoalter/scrubber.dm
Labels: Changes Requested, Fix

#1026 Made a check for map load before creating a new proxy assembly/air co…
  code/game/objects/items/weapons/tanks/tanks.dm
Labels: Approved for DEV, Awaiting Travis, Fix

#1027 Changes the Medical Heavyduty Voidsuit to Unprepared (Bug workaround)
  code/datums/supplypacks/medical.dm
Labels: Approved for DEV, Awaiting Travis, Fix

#1039 Made the folded roller bed fit in a backpack, so they're a bit more c…
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Approved for DEV, Awaiting Travis, Feature Change

#1064 Fixes SSasteroid keeping players and SSautosave not announcing correc…
  code/controllers/subsystems/SSair.dm
  code/controllers/subsystems/SSalarm.dm
  code/controllers/subsystems/SSasteroid.dm
  code/controllers/subsystems/SSatoms.dm
  code/controllers/subsystems/SSautosave.dm
  code/controllers/subsystems/SSchemistry.dm
  code/controllers/subsystems/SSevent.dm
  code/controllers/subsystems/SSgarbage.dm
  code/controllers/subsystems/SSinactivity.dm
  code/controllers/subsystems/SSlighting.dm
  code/controllers/subsystems/SSmachines.dm
  code/controllers/subsystems/SSmapping.dm
  code/controllers/subsystems/SSopen_space.dm
  code/controllers/subsystems/SSplants.dm
  code/controllers/subsystems/SSradiation.dm
  code/controllers/subsystems/SSshuttle.dm
  code/controllers/subsystems/SSskybox.dm
  code/controllers/subsystems/SSsun.dm
  code/controllers/subsystems/SSsupply.dm
  code/controllers/subsystems/SStgui.dm
  code/controllers/subsystems/SStimer.dm
  code/controllers/subsystems/SStrade.dm
  code/controllers/subsystems/SSturbolift.dm
  code/controllers/subsystems/SSwireless.dm
  code/controllers/subsystems/initialization/SSearly.dm
  code/controllers/subsystems/initialization/SSlate.dm
  code/controllers/subsystems/initialization/SSmaterials.dm
  code/controllers/subsystems/processing/SSairflow.dm
  code/controllers/subsystems/processing/SScircuit.dm
  code/controllers/subsystems/processing/SSfast_process.dm
  code/controllers/subsystems/processing/SSicon_updates.dm
  code/controllers/subsystems/processing/SSmobs.dm
  code/controllers/subsystems/processing/SSnano.dm
  code/controllers/subsystems/processing/SSobj.dm
  code/controllers/subsystems/processing/SSprocessing.dm
  code/controllers/subsystems/processing/SSturf.dm
  code/controllers/subsystems/processing/SSvines.dm
  code/datums/ai/ai.dm
  code/game/machinery/acting_items.dm
  code/modules/mob/living/silicon/ai/ai_holo.dm
  persistentss13.dme
Labels: Awaiting Review, Fix

#1068 Added bombsuit crate to sec and science supply categories
  code/datums/supplypacks/science.dm
  code/datums/supplypacks/security.dm
  code/modules/clothing/shoes/miscellaneous.dm
  html/changelogs/psycommando-pr-1068.yml
Labels: Approved for DEV, Awaiting Travis, Feature Change

#1065 Stackable ore
  code/datums/trading/ai.dm
  code/datums/trading/goods.dm
  code/datums/trading/unique.dm
  code/game/gamemodes/meteor/meteors.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/storage/specialized.dm
  code/modules/atmospherics/components/binary_devices/oxyregenerator.dm
  code/modules/item_worth/Value_procs/obj/items.dm
  code/modules/item_worth/worths_list.dm
  code/modules/materials/_materials.dm
  code/modules/materials/definitions/materials_metal.dm
  code/modules/materials/definitions/materials_mineral.dm
  code/modules/materials/definitions/materials_stone.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials_ore.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/drilling/scanner.dm
  code/modules/mining/machinery/_mineral.dm
  code/modules/mining/machinery/mineral_console.dm
  code/modules/mining/machinery/mineral_processor.dm
  code/modules/mining/machinery/mineral_stacker.dm
  code/modules/mining/machinery/mineral_unloader.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/satchel_ore_boxdm.dm
  code/modules/mob/living/simple_animal/hostile/creature.dm
  code/modules/mob/living/simple_animal/hostile/voxslug.dm
  code/modules/random_map/automata/caves.dm
  code/modules/random_map/noise/ore.dm
  code/modules/xenoarcheaology/finds/finds.dm
  code/modules/xenoarcheaology/sampling.dm
  code/modules/xenoarcheaology/tools/geosample_scanner.dm
Labels: Awaiting Review, Feature Change, Fix

#1071 Update hydroponics tray right away
  code/modules/hydroponics/trays/tray.dm
Labels: Changes Requested, Feature Change, Fix
