Repository Persistent-SS13/Persistent-Bay, pull requests merged in 2018-09, with the labels that each got.

#544 Adds drains and evaporation to PUDDLES
  code/game/objects/effects/chem/chempuddle.dm
  code/game/objects/effects/chem/drain.dm
  code/game/objects/structures/watercloset.dm
  code/modules/materials/material_recipes.dm
  code/modules/reagents/Chemistry-Holder.dm
  icons/effects/puddle_chem.dmi
  icons/obj/watercloset.dmi
  persistentss13.dme
Labels: Feature Change, Fix, New Feature

#545 Fixes electric chair functionality AND duplication glitch
  code/game/objects/items/devices/radio/electropack.dm
  code/game/objects/structures/electricchair.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Fix

#547 Fixes 100% chance of spilling when transferring reagents from a holder to holer
  code/modules/reagents/reagent_containers.dm
Labels: Hotfix

#560 The Designer feature
  code/modules/designer/designer.dm
  html/designer.html
  persistentss13.dme
Labels: New Feature

#583 Adds new subsystem for user mob processing - Decreases other mob's process priority
  code/__defines/subsystem-priority.dm
  code/controllers/subsystems/processing/mobs.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Feature Change, Hotfix

#589 Fixes the new subsystem not letting you create a new character
  code/modules/mob/mob.dm
Labels: Hotfix

#591 Reverts my own shit. New SS for hostile mobs only for seperated, lower priority processing
  code/__defines/subsystem-priority.dm
  code/controllers/subsystems/processing/mobs.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Hotfix

#595 Ore processor should no longer eat your shit.
  code/modules/mining/machinery/mineral_processor.dm
Labels: Fix

#605 REVERT HOSTILE SS (In case we need)
  code/controllers/subsystems/processing/mobs.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Do Not Merge, Hotfix

#586 State of Matter Pt.2
  code/__defines/atmospherics.dm
  code/__defines/math_physics.dm
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/objects/effects/chem/chempuddle.dm
  code/game/objects/effects/chem/drain.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/structures/watercloset.dm
  code/modules/ZAS/Zone.dm
  code/modules/_chemistry_update/ARO.dm
  code/modules/_chemistry_update/chempuddle.dm
  code/modules/_chemistry_update/drain.dm
  code/modules/atmospherics/atmos_primitives.dm
  code/modules/atmospherics/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/components/trinary_devices/filter.dm
  code/modules/atmospherics/components/unary/outlet_injector.dm
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/materials/material_recipes.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/xgm/gases.dm
  code/modules/xgm/xgm_gas_data.dm
  icons/effects/puddle_chem.dmi
  icons/obj/pipe-item.dmi
  icons/obj/watercloset.dmi
  persistentss13.dme
Labels: Do Not Merge, Feature Change, New Feature

#592 Printer
  code/game/machinery/bioprinter.dm
  code/modules/research/designs.dm
Labels: Awaiting Review, Feature Change

#683 Adds Radio-less Airlock cycling & linking
  code/__defines/norad.dm
  code/game/machinery/autolathe_datums.dm
  code/game/machinery/doors/airlock.dm
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/atmospherics/components/unary/vent_scrubber.dm
  code/modules/norad_controller/_frames.dm
  code/modules/norad_controller/airlock_controller.dm
  code/modules/norad_controller/airlock_sensor.dm
  nano/templates/advanced_airlock_console_norad.tmpl
  persistentss13.dme
Labels: Feature Change, New Feature

#697 SoM Pt.2 RE-introduction
  code/__defines/atmospherics.dm
  code/__defines/math_physics.dm
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/atmoalter/canister.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/objects/effects/chem/chempuddle.dm
  code/game/objects/effects/chem/drain.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/structures/watercloset.dm
  code/modules/ZAS/Zone.dm
  code/modules/_chemistry_update/ARO.dm
  code/modules/_chemistry_update/chempuddle.dm
  code/modules/_chemistry_update/drain.dm
  code/modules/atmospherics/atmos_primitives.dm
  code/modules/atmospherics/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/components/trinary_devices/filter.dm
  code/modules/atmospherics/components/unary/outlet_injector.dm
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/materials/material_recipes.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/xgm/gases.dm
  code/modules/xgm/xgm_gas_data.dm
  html/changelogs/ingles98-PR-697.yml
  icons/effects/puddle_chem.dmi
  icons/obj/pipe-item.dmi
  persistentss13.dme
Labels: Feature Change, Fix, New Feature

#711 (RE-ADDED)Updates the changelog to Baystation's model and tweaks it to Persistent
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/AutoChangeLog-pr-19694.yml
  html/changelogs/AutoChangeLog-pr-19696.yml
  html/changelogs/AutoChangeLog-pr-19711.yml
  html/changelogs/Kurgis-pr-550.yml
  html/templates/header.html
  tools/GenerateChangelog/install_PyYAML.bat
Labels: Fix

#705 Turrets should properly assess bots
  code/game/machinery/portable_turret.dm
  html/changelogs/rhicora-pr-705.yml
Labels: Approved

#748 Update windowdoor.dm
  code/game/machinery/doors/windowdoor.dm
Labels: Hotfix
