Repository Persistent-SS13/Persistent-Bay, pull requests merged in 2019-07, with the labels that each got.

#1255 Minable ices
  code/__defines/materials.dm
  code/modules/materials/_materials.dm
  code/modules/materials/definitions/material_ices.dm
  code/modules/materials/definitions/materials_metal.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials_ore.dm
  code/modules/materials/materials_rods.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/mine_items.dm
  code/modules/random_map/automata/caves.dm
  code/modules/random_map/noise/ore.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Acids.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Metals.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/recipes/food.dm
  code/modules/reagents/recipes/materials.dm
  code/modules/reagents/recipes/others.dm
  persistentss13.dme
Labels: Approved for DEV, Feature Change, New Feature

#1264 makes the dropper not stab people in the eyes
  code/modules/reagents/reagent_containers/dropper.dm
Labels: Fix

#1262 Added saved vars to grown plants
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Fix

#1263 Material stacks extra hotfix
  code/game/objects/items/stacks/stack.dm
  code/modules/materials/material_sheets.dm
Labels: Fix

#1265 despawn now link in chat when cryo-ing
  code/game/machinery/cryopod.dm
Labels: New Feature

#1269 Bay "Ambient Occlusion"
  code/__defines/_planes+layers.dm
  code/__defines/ao.dm
  code/__defines/ao_misc.dm
  code/__defines/colors.dm
  code/__defines/directions.dm
  code/__defines/turfs.dm
  code/controllers/subsystems/ao.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/game/turfs/turf_ao.dm
  code/game/turfs/turf_changing.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/multiz/movement.dm
  code/modules/multiz/turf.dm
  code/modules/multiz/zshadow.dm
  icons/mob/light_overlays.dmi
  icons/turf/flooring/dirt.dmi
  icons/turf/flooring/shadows.dmi
  persistentss13.dme
Labels: New Feature

#1270 Adds the absolutely essential reagent heater and coolers to service fab
  code/modules/research/fabricators/service_fabricator.dm
Labels: Hotfix

#1266 made a quick recipe for whiskey + koolan drink mixes
  code/modules/reagents/recipes/alcohol.dm
  persistentss13.dme
Labels: Hotfix

#1272 Made many more programs compatible with tablets, laptops, and PDAs an…
  code/game/machinery/cloning.dm
  code/modules/modular_computers/file_system/programs/business/business_core.dm
  code/modules/modular_computers/file_system/programs/business/library_control.dm
  code/modules/modular_computers/file_system/programs/business/management.dm
  code/modules/modular_computers/file_system/programs/business/news_control.dm
  code/modules/modular_computers/file_system/programs/business/registration.dm
  code/modules/modular_computers/file_system/programs/business/stockholders.dm
  code/modules/modular_computers/file_system/programs/command/buisness.dm
  code/modules/modular_computers/file_system/programs/command/card.dm
  code/modules/modular_computers/file_system/programs/command/card2.dm
  code/modules/modular_computers/file_system/programs/command/comm.dm
  code/modules/modular_computers/file_system/programs/command/faction_core.dm
  code/modules/modular_computers/file_system/programs/democracy/citycouncil.dm
  code/modules/modular_computers/file_system/programs/democracy/civil_laws.dm
  code/modules/modular_computers/file_system/programs/democracy/criminal_laws.dm
  code/modules/modular_computers/file_system/programs/democracy/democracy_core.dm
  code/modules/modular_computers/file_system/programs/democracy/elections.dm
  code/modules/modular_computers/file_system/programs/democracy/executive_policy.dm
  code/modules/modular_computers/file_system/programs/democracy/governor.dm
  code/modules/modular_computers/file_system/programs/democracy/judge.dm
  code/modules/modular_computers/file_system/programs/democracy/tax_laws.dm
  code/modules/modular_computers/file_system/programs/democracy/verdicts.dm
  code/modules/modular_computers/file_system/programs/generic/configurator.dm
  code/modules/modular_computers/file_system/programs/generic/contracts.dm
  code/modules/modular_computers/file_system/programs/generic/crew_manifest.dm
  code/modules/modular_computers/file_system/programs/generic/email_client.dm
  code/modules/modular_computers/file_system/programs/generic/file_browser.dm
  code/modules/modular_computers/file_system/programs/generic/id_management.dm
  code/modules/modular_computers/file_system/programs/generic/invoicing.dm
  code/modules/modular_computers/file_system/programs/generic/library.dm
  code/modules/modular_computers/file_system/programs/generic/materialmarket.dm
  code/modules/modular_computers/file_system/programs/generic/news_browser.dm
  code/modules/modular_computers/file_system/programs/generic/ntdownloader.dm
  code/modules/modular_computers/file_system/programs/generic/ntnrc_client.dm
  code/modules/modular_computers/file_system/programs/generic/ntrouter.dm
  code/modules/modular_computers/file_system/programs/generic/nttransfer.dm
  code/modules/modular_computers/file_system/programs/generic/personal.dm
  code/modules/modular_computers/file_system/programs/medical/clone_manager.dm
Labels: Feature Change, Hotfix

#1271 Add the oxygen regenerator to the fab since it was missing....
  code/modules/research/fabricators/autotailor_standard.dm
  code/modules/research/fabricators/circuit_fabricator.dm
  code/modules/research/fabricators/engineering_fabricator.dm
Labels: Feature Change, Fix

#1268 Tweaked a few gun names and weights
  code/__defines/math_physics.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/secure.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/launcher/grenade_launcher.dm
  code/modules/projectiles/guns/launcher/net.dm
  code/modules/projectiles/guns/launcher/pneumatic.dm
  code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
  code/modules/projectiles/guns/projectile/revolvers/capgun.dm
  code/modules/projectiles/guns/projectile/revolvers/deckard.dm
  code/modules/projectiles/guns/projectile/revolvers/detective.dm
  code/modules/projectiles/guns/projectile/revolvers/foundation.dm
  code/modules/projectiles/guns/projectile/revolvers/holdout.dm
  code/modules/projectiles/guns/projectile/revolvers/mateba.dm
  code/modules/projectiles/guns/projectile/revolvers/solid38.dm
  code/modules/projectiles/guns/projectile/revolvers/webley.dm
  code/modules/projectiles/guns/projectile/rifles/sniper.dm
  code/modules/projectiles/guns/projectile/shotguns/explo_shotgun.dm
  code/modules/psionics/equipment/foundation_weapon.dm
  persistentss13.dme
Labels: Feature Change

#1267 Added droppers to med fab
  code/modules/research/fabricators/general_fabricator.dm
  code/modules/research/fabricators/medical_fabricator.dm
Labels: Hotfix

#1279 Travis
  code/_helpers/global_access.dm
  code/unit_tests/mob_tests.dm
  test/check-paths.sh
  test/run-test.sh
Labels: Awaiting Travis

#1278 Egg reduction and half chicken meat/Seed extractor rng
  code/game/machinery/seed_extractor.dm
  code/modules/hydroponics/beekeeping/beehive.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/research/fabricators/engineering_fabricator.dm
Labels: Approved for DEV, Awaiting Travis, Feature Change

#1293 Don't hose new botanists.
  code/modules/hydroponics/beekeeping/beehive.dm
Labels: Approved for DEV, Fix

#1292 Adds honey crystallization
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Awaiting Review, New Feature

#1291 Plantfix
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/trays/tray.dm
Labels: Awaiting Review, Hotfix

#1298 fixes ore processor and other such things
  code/modules/materials/definitions/materials_metal.dm
  code/modules/mining/machinery/mineral_processor.dm
Labels: Failed Basic, Fix

#1290 Adds new phorostimulant and some more addictions
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Failed Basic, Feature Change, New Feature

#1314 Clarify prompt for email recipient
  code/modules/modular_computers/file_system/programs/generic/email_client.dm
Labels: Approved, Fix

#1313 Fix blueprints
  code/game/objects/items/blueprints.dm
Labels: Approved, Hotfix

#1316 Adds 2 Jukebox Songs
  code/game/machinery/jukebox.dm
  sound/music/jukebox/Bluespace Ocean.ogg
  sound/music/jukebox/This is Rain.ogg
Labels: Approved

#1315 Labor Exile Implants
  code/modules/persistence_modules/laborexile/exile.dm
  persistentss13.dme
Labels: Awaiting Review, New Feature

#1318 Other Coffee Dispenser Directions
  icons/obj/chemical.dmi
Labels: Approved

#1320 Add missing material recipes
  code/__defines/materials.dm
  code/_helpers/global_access.dm
  code/game/machinery/wall_frames.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/hydroponics/beekeeping/beehive.dm
  code/modules/item_worth/worths_list.dm
  code/modules/materials/definitions/materials_organic.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/recipes_furniture.dm
  code/modules/materials/recipes_items.dm
  code/modules/materials/recipes_storage.dm
  code/modules/materials/recipes_structures.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
Labels: Awaiting Review, Feature Change

#1325 Added some missing items to fabricators
  code/modules/research/fabricator.dm
  code/modules/research/fabricators/consumer_fabricator.dm
  code/modules/research/fabricators/engineering_fabricator.dm
  code/modules/research/fabricators/medical_fabricator.dm
  code/modules/research/fabricators/service_fabricator.dm
Labels: Awaiting Review, Feature Change, Fix

#1329 Removed some debug spam on human mob damage
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/organs/external/_external_damage.dm
Labels: Awaiting Review, Fix

#1326 Made sure items properly compute their temperature coefficient
  code/game/atoms_temperature.dm
  code/modules/reagents/heat_sources/_heat_source.dm
Labels: Awaiting Review, Fix

#1322 Graffities now check for something else than sharpness
  code/game/objects/items.dm
  code/game/objects/items/weapons/tools/scissors.dm
  code/game/objects/items/weapons/tools/screwdriver.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/turfs/turf.dm
  code/modules/persistence/graffiti.dm
Labels: Awaiting Review, Feature Change, Fix

#1324 Added some new alcohol recipes
  code/modules/hydroponics/seed_datums.dm
  code/modules/materials/definitions/materials_metal.dm
  code/modules/materials/definitions/materials_mineral.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/recipes/alcohol.dm
  code/modules/reagents/recipes/food.dm
  code/modules/reagents/recipes/materials.dm
  code/modules/reagents/recipes/others.dm
Labels: Awaiting Review, Feature Change, Fix

#1319 Fix broken sprites
  code/game/objects/items/weapons/melee/misc.dm
  code/modules/paperwork/pen.dm
Labels: Awaiting Review, Fix

#1323 make sleepers and dispensers able to accept reagent cartridges again
  code/datums/extensions/label.dm
  code/game/machinery/Sleeper.dm
  code/modules/reagents/dispenser/cartridge.dm
  code/modules/reagents/dispenser/cartridge_spawn.dm
  code/modules/reagents/dispenser/dispenser2.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
Labels: Awaiting Review, Fix

#1327 Adding misc save vars to several items missing them
  code/game/atoms.dm
  code/game/objects/items/contraband.dm
  code/game/objects/items/latexballoon.dm
  code/game/objects/items/plunger.dm
  code/game/objects/structures/coathanger.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/electricchair.dm
  code/game/objects/structures/extinguisher.dm
  code/game/objects/structures/holosigns.dm
  code/game/objects/structures/iv_drip.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/mop_bucket.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/wall_frame.dm
  code/game/objects/structures/wall_items/posters.dm
  code/game/objects/structures/wall_items/signs.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/projectiles/guns/launcher/pneumatic.dm
  code/modules/projectiles/guns/magnetic/magnetic_construction.dm
Labels: Awaiting Review, Fix

#1321 Fixing SSautosave
  code/__defines/subsystems.dm
  code/controllers/subsystems/autosave.dm
  code/controllers/subsystems/event.dm
Labels: Awaiting Review, Fix

#1333 For some reasons the makeshift bandage definition got lost in the commits..
  code/game/objects/items/stacks/medical.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/recipes_items.dm
Labels: Hotfix

#1334 shutuptravis
  code/_helpers/global_access.dm
  code/datums/extensions/multitool/multitool.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/recipes/alcohol.dm
  test/run-test.sh
Labels: Hotfix

#1332 Fix missing recipes for some material stacks
  code/modules/materials/material_recipes.dm
Labels: Hotfix

#1336 Designs should now save properly (Includes important notes about saved vars list)
  code/_helpers/global_access.dm
  code/modules/designer/canvas.dm
  code/modules/designer/designer.dm
  code/modules/world_save/map_storage.dm
  test/run-test.sh
Labels: Fix

#1338 Removes duplicate device cell entry
  code/modules/research/fabricators/engineering_fabricator.dm
Labels: Approved, Fix

#1337 Fix the cream recipe conflicting with the cheese recipe + tweak reagent heater
  code/modules/reagents/heat_sources/_heat_source.dm
  code/modules/reagents/recipes/food.dm
Labels: Hotfix

#1330 New coffee plant sprites
  icons/obj/hydroponics_growing.dmi
Labels: Approved, Feature Change

#1339 adds missing voidsuits
  code/modules/research/fabricators/eva_fabricator.dm
Labels: Approved, Feature Change

#1345 voidsuit fixes
  code/modules/research/fabricators/eva_fabricator.dm
Labels: Approved, Hotfix

#1351 Welder won't toggle the blind bit anymore
  code/game/objects/items/weapons/tools/welder.dm
  code/modules/organs/internal/eyes.dm
Labels: Fix

#1349 Changed premium whiskey and rum recipes
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/recipes/alcohol.dm
Labels: Feature Change, Fix

#1348 add icecream vat to fab, and make it buildable
  code/game/machinery/kitchen/icecream.dm
  code/game/objects/items/weapons/circuitboards/machinery/kitchen.dm
  code/modules/research/fabricators/service_fabricator.dm
Labels: New Feature

#1347 probably fix missing account owner name
  code/modules/world_save/map_storage.dm
Labels: Fix

#1359 made organs slightly tougher
  code/modules/organs/_organ_setup.dm
  code/modules/organs/internal/eyes.dm
  code/modules/organs/internal/heart.dm
  code/modules/organs/internal/kidneys.dm
  code/modules/organs/internal/lungs.dm
  code/modules/organs/internal/stomach.dm
Labels: Feature Change
