Repository Persistent-SS13/Persistent-Bay, pull requests merged in 2019-06, with the labels that each got.

#1208 Shovels can now dig sand.
  code/modules/mining/mine_turfs.dm
Labels: Approved for DEV, Awaiting Travis, Fix

#1205 UI when clicking mirrors now appear again
  code/game/objects/items/weapons/storage/wall_mirror.dm
Labels: Approved for DEV, Fix

#1223 Hydro stuff + save fixing for trays and added plant scanner to service fab
  code/modules/hydroponics/trays/tray.dm
  code/modules/hydroponics/trays/tray_process.dm
  code/modules/hydroponics/trays/tray_update_icons.dm
  code/modules/research/fabricators/service_fabricator.dm
Labels: Approved for DEV, Feature Change, Fix
