Repository Persistent-SS13/Persistent-Bay, pull requests merged in 2019-08, with the labels that each got.

#1375 Some more fixes for the last PR
  code/controllers/subsystems/atoms.dm
  code/controllers/subsystems/autosave.dm
  code/game/area/areas.dm
  code/game/machinery/bioprinter.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/machinery/floodlight.dm
  code/game/machinery/machinery.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/recycler.dm
  code/game/machinery/vending.dm
  code/game/objects/items/blueprints.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/robot/robot_frame.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/objs.dm
  code/game/objects/structures.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/railing.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/wall_icon.dm
  code/modules/admin/callproc/callproc.dm
  code/modules/assembly/infrared.dm
  code/modules/atmospherics/pipes.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/codex/codex_client.dm
  code/modules/factions/docking_beacon.dm
  code/modules/materials/material_sheets.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mob/grab/grab_datum.dm
  code/modules/mob/grab/grab_object.dm
  code/modules/mob/grab/normal/norm_aggressive.dm
  code/modules/mob/living/bot/farmbot.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/mob.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/organs/internal/lungs.dm
  code/modules/paperwork/paper.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/recycling/disposal-construction.dm
  code/modules/research/fabricator.dm
  code/modules/research/fabricators/service_fabricator.dm
  code/modules/shuttles/shuttle_engines.dm
Labels: Hotfix

#1417 [Recovery PR] Makes armor description not crash when dealing with some particular d…
  code/_helpers/lists.dm
  code/modules/examine/descriptions/armor.dm
Labels: Fix

#1416 [Recovery PR] rewrite the clonepod so it works now
  code/game/dna/dna2.dm
  code/game/machinery/cloning.dm
  code/modules/modular_computers/file_system/program_events.dm
  code/modules/modular_computers/file_system/programs/medical/clone_manager.dm
  code/modules/modular_computers/hardware/scanners/scanner_medical.dm
Labels: Fix

#1413 [Recovery PR] Adds the missing revolver + a few tiny things
  code/modules/projectiles/ammunition/boxes.dm
  code/modules/projectiles/guns/projectile/revolvers/autorevolver.dm
  code/modules/projectiles/guns/projectile/revolvers/solid38.dm
  code/modules/research/fabricators/weapons_fabricator.dm
  persistentss13.dme
Labels: Fix

#1410 [Recovery PR] Added signs to the fab
  code/modules/research/fabricators/engineering_fabricator.dm
Labels: New Feature

#1405 [Recovery PR] fix laces showing up multiple time on the same person
  code/_onclick/hud/ability_screen_objects.dm
  code/_onclick/hud/action.dm
  code/controllers/subsystems/processing/icon_updates.dm
  code/modules/mob/living/carbon/brain/LMI.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/carbon/brain/brain.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/lace/lace.dm
  code/modules/organs/internal/stack.dm
  code/modules/organs/organ.dm
Labels: Fix

#1400 [Recovery PR] Save the vars for the tape recorder + fix editing tapes
  code/game/objects/items/devices/taperecorder.dm
Labels: Fix

#1386 [Recovery PR] Reduce useless calls to base Process() proc
  code/game/machinery/atmo_control.dm
  code/game/machinery/atmoalter/meter.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/Operating.dm
  code/game/machinery/computer/pod.dm
  code/game/machinery/doors/airlock_control/airlock_sensor.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/embedded_controller/airlock_controllers_dummy.dm
  code/game/machinery/machinery.dm
  code/game/machinery/recharger.dm
  code/game/machinery/recycler.dm
  code/game/machinery/robot_fabricator.dm
  code/game/mecha/mech_bay.dm
  code/modules/norad_controller/airlock_sensor.dm
Labels: Fix

#1411 [Recovery PR] Icon update queue now check if things are deleting when updating icons
  code/game/atoms.dm
  code/game/machinery/atmoalter/portable_atmospherics.dm
Labels: Fix

#1408 [Recovery PR] Fix calls to audible message with bad parameters causing runtimes
  code/game/machinery/requests_console.dm
  code/game/objects/items/weapons/newspaper.dm
  code/modules/power/apc.dm
  code/modules/xenoarcheaology/tools/geosample_scanner.dm
Labels: Fix

#1407 [Recovery PR] Made the keyprinter actually work
  code/controllers/communications.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/keyprinter.dm
  code/game/objects/items/devices/radio/radio.dm
Labels: Fix

#1382 [Recovery PR] We were using an old duplicate version of the iv drip for some reasons
  code/game/machinery/iv_drip.dm
  code/game/objects/structures/iv_drip.dm
  code/modules/materials/recipes_structures.dm
  persistentss13.dme
Labels: Fix

#1396 [Recovery PR] fix typo in material name for the light replacer
  code/modules/research/fabricators/engineering_fabricator.dm
Labels: Hotfix

#1399 [Recovery PR] fix missing button frame icon
  code/game/machinery/wall_frames.dm
Labels: Fix

#1397 [Recovery PR] add fake book storage item to fab
  code/modules/research/fabricators/consumer_fabricator.dm
  code/modules/torch/items/items.dm
Labels: Feature Change, Fix

#1395 [Recovery PR] sticky pads are in the fab now
  code/modules/research/fabricators/general_fabricator.dm
Labels: Hotfix

#1398 [Recovery PR] fixes queue removal on fabricator + runtime
  code/modules/research/fabricator.dm
Labels: Fix

#1384 [Recovery PR] Mass driver now properly refers to its circuit board
  code/game/machinery/mass_driver.dm
  code/modules/research/fabricators/circuit_fabricator.dm
Labels: Fix

#1401 [Recovery PR] make holopads actually use the base code for assembly and disassembly
  code/game/machinery/hologram.dm
Labels: Fix

#1412 [Recovery PR] Make reagents dispensers refillable + fix some recipes
  code/game/atoms_fluids.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/structures/tank_dispenser.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/recipes_furniture.dm
  code/modules/materials/recipes_storage.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/dispenser/cartridge.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/drinkingglass/drinkingglass.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/reagents/recipes/alcohol.dm
  code/modules/reagents/recipes/others.dm
  code/modules/reagents/structures/beerkeg.dm
  code/modules/reagents/structures/fuel_tank.dm
  code/modules/research/fabricators/autotailor_accessories.dm
Labels: Fix

#1406 [Recovery PR] Clear destroyed watchers from the global watcher list
  code/datums/observation/observation.dm
Labels: Fix

#1409 [Recovery PR] Fix missing typepath
  code/game/objects/items/weapons/grenades/explosive.dm
Labels: Fix

#1404 [Recovery PR] Stuff that should save their base icon states should do it properly now
  code/datums/extensions/appearance/base_icon_state.dm
  code/datums/extensions/extensions.dm
Labels: Hotfix

#1402 [Recovery PR] Make firedoor assemblies rotate when alt-clicked
  code/game/machinery/doors/firedoor_assembly.dm
Labels: Fix

#1403 [Recovery PR] fire alarms save their construction state
  code/game/machinery/fire_alarm.dm
Labels: Fix

#1424 Removing some slimes
  code/modules/mob/living/carbon/xenobiological/items.dm
  code/modules/mob/living/carbon/xenobiological/subtypes.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/recipes/slimes.dm
Labels: Feature Change
