Repository Persistent-SS13/Persistent-Bay, pull requests merged in 2019-09, with the labels that each got.

#1436 Fixes stockholder revenue
  code/modules/factions/faction.dm
Labels: Approved, Fix

#1435 Resomi fixes
  code/__defines/culture.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/culture_descriptor/culture/cultures_resomi.dm
  code/modules/mob/language/alien/raptor.dm
  code/modules/species/station/resomi.dm
  icons/obj/clothing/species/resomi/uniform.dmi
  persistentss13.dme
Labels: Approved, Hotfix

#1432 Nanopaste for limbs
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/nanopaste.dm
Labels: Changes Requested, Failed Basic, New Feature

#1434 Vending machine ui tweaks
  nano/templates/vending_machine.tmpl
Labels: Feature Change, Fix

#1431 Update subtypes.dm
  code/modules/mob/living/carbon/xenobiological/subtypes.dm
Labels: Approved, Feature Change

#1433 [Recovery PR] Bunch of little things I couldn't fit in any category, and didn't want to make 10,000 prs for one line changes
  code/game/atoms_movable.dm
  code/game/gamemodes/cult/runes.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/cracker.dm
  code/game/objects/buckling.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/lighter.dm
  code/game/objects/items/weapons/storage/firstaid.dm
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/game/objects/items/weapons/tools/scissors.dm
  code/game/objects/items/weapons/tools/welder.dm
  code/game/objects/items/weapons/tools/welders/weldbackpack.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/rubble.dm
  code/game/objects/structures/safe.dm
  code/game/objects/structures/showcase.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/atmospherics/pipes.dm
  code/modules/atmospherics/pipes/simple_pipes.dm
  code/modules/food/replicator.dm
  code/modules/locks/lock.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/death.dm
  code/modules/mob/living/simple_animal/hostile/bat.dm
  code/modules/overmap/exoplanets/turfs.dm
  code/modules/power/apc.dm
Labels: Fix

#1430 Rebalance device cells, egun shot costs
  code/modules/power/cell.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/research/fabricators/engineering_fabricator.dm
  code/modules/research/research.dm
  icons/obj/power.dmi
Labels: Approved, Feature Change

#1441 save defib battery
  code/game/objects/items/weapons/defib.dm
Labels: Fix

#1438 More Resomi Fixes
  code/modules/research/fabricators/eva_fabricator.dm
  code/modules/species/station/resomi.dm
  code/modules/sprite_accessories/_accessory_hair.dm
Labels: Fix

#1440 clothing description should not runtime anymore
  code/modules/codex/entries/clothing.dm
Labels: Fix
